# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_grpc.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12product_grpc.proto\"\xeb\x01\n\x07Product\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x13\n\x0bsubcategory\x18\x04 \x01(\t\x12\x12\n\nsubproduct\x18\x05 \x01(\t\x12\x17\n\x0flink_to_product\x18\x06 \x01(\t\x12\x17\n\x0flink_to_picture\x18\x07 \x01(\t\x12\r\n\x05\x62rand\x18\x08 \x01(\t\x12\x0e\n\x06weight\x18\t \x01(\x05\x12\x13\n\x04pfck\x18\n \x01(\x0b\x32\x05.Pfck\x12\x13\n\x0binformation\x18\x0b \x01(\t\x12\x16\n\x06stores\x18\x0c \x03(\x0b\x32\x06.StoreJ\x04\x08\x01\x10\x02\"O\n\x04Pfck\x12\x0f\n\x07protein\x18\x02 \x01(\x01\x12\x0b\n\x03\x66\x61t\x18\x03 \x01(\x01\x12\x15\n\rcarbohydrates\x18\x04 \x01(\x01\x12\x0c\n\x04kcal\x18\x05 \x01(\x01J\x04\x08\x01\x10\x02\"A\n\x05Store\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x15\n\rlink_to_store\x18\x04 \x01(\tJ\x04\x08\x01\x10\x02\",\n\x0fProductResponse\x12\x19\n\x07product\x18\x01 \x01(\x0b\x32\x08.Product\"\'\n\rSearchRequest\x12\x16\n\x0esearch_request\x18\x01 \x01(\t\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"-\n\x10ProductResponses\x12\x19\n\x07product\x18\x01 \x03(\x0b\x32\x08.Product\"\x07\n\x05\x45mpty2\x9f\x01\n\x0eProductService\x12\x32\n\rSearchProduct\x12\x0e.SearchRequest\x1a\x11.ProductResponses\x12/\n\nGetProduct\x12\x0f.ProductRequest\x1a\x10.ProductResponse\x12(\n\x0bGetProducts\x12\x06.Empty\x1a\x11.ProductResponsesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=23
  _globals['_PRODUCT']._serialized_end=258
  _globals['_PFCK']._serialized_start=260
  _globals['_PFCK']._serialized_end=339
  _globals['_STORE']._serialized_start=341
  _globals['_STORE']._serialized_end=406
  _globals['_PRODUCTRESPONSE']._serialized_start=408
  _globals['_PRODUCTRESPONSE']._serialized_end=452
  _globals['_SEARCHREQUEST']._serialized_start=454
  _globals['_SEARCHREQUEST']._serialized_end=493
  _globals['_PRODUCTREQUEST']._serialized_start=495
  _globals['_PRODUCTREQUEST']._serialized_end=531
  _globals['_PRODUCTRESPONSES']._serialized_start=533
  _globals['_PRODUCTRESPONSES']._serialized_end=578
  _globals['_EMPTY']._serialized_start=580
  _globals['_EMPTY']._serialized_end=587
  _globals['_PRODUCTSERVICE']._serialized_start=590
  _globals['_PRODUCTSERVICE']._serialized_end=749
# @@protoc_insertion_point(module_scope)
