
CREATE DATABASE IF NOT EXISTS all_links;

\c all_links;


CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS subcategories (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS subproducts (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    subcategory_id INTEGER NOT NULL REFERENCES subcategories(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    subproduct_id INTEGER NOT NULL REFERENCES subproducts(id) ON DELETE CASCADE ON UPDATE CASCADE
);
